// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATXckpUERWbaG1CK1l0spRLGycc69AlPc',
    appId: '1:45598162080:web:0748145452a429d1f79dc5',
    messagingSenderId: '45598162080',
    projectId: 'agriwealth-43a77',
    authDomain: 'agriwealth-43a77.firebaseapp.com',
    storageBucket: 'agriwealth-43a77.firebasestorage.app',
    measurementId: 'G-YTH1HPTXWX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCENIZD-CkQaz0OR8Jr8w8nCpGP5zHhlW8',
    appId: '1:45598162080:android:c45b6d696f313551f79dc5',
    messagingSenderId: '45598162080',
    projectId: 'agriwealth-43a77',
    storageBucket: 'agriwealth-43a77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlA1I7DdQBxA71MafLookwzjLhOot_24M',
    appId: '1:45598162080:ios:57b2a731c202445df79dc5',
    messagingSenderId: '45598162080',
    projectId: 'agriwealth-43a77',
    storageBucket: 'agriwealth-43a77.firebasestorage.app',
    iosBundleId: 'com.example.agriwealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlA1I7DdQBxA71MafLookwzjLhOot_24M',
    appId: '1:45598162080:ios:b96cddc1ca5f2ab4f79dc5',
    messagingSenderId: '45598162080',
    projectId: 'agriwealth-43a77',
    storageBucket: 'agriwealth-43a77.firebasestorage.app',
    iosBundleId: 'com.example.wise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATXckpUERWbaG1CK1l0spRLGycc69AlPc',
    appId: '1:45598162080:web:d3cae109dd26e97af79dc5',
    messagingSenderId: '45598162080',
    projectId: 'agriwealth-43a77',
    authDomain: 'agriwealth-43a77.firebaseapp.com',
    storageBucket: 'agriwealth-43a77.firebasestorage.app',
    measurementId: 'G-3DWXNKL2N2',
  );

}